name: UltimateGuild
version: 1.0.0
main: me.ayolk.ultimateguild.UltimateGuild
authors: [ AyolK ]
depend: [MythicMobs,PlaceholderAPI]
api-version: 1.18.2
commands:
  UltimateGuild:
    aliases:
      - ug
  UltimateGuildAdmin:
    aliases:
      - ugadmin

